# Generated by Django 4.2.16 on 2024-11-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competicao',
            name='vencedores',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='clube_atual',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='clubes',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='competicao',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='associacao',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='extinto',
        ),
        migrations.AlterField(
            model_name='clube',
            name='alcunha',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clube',
            name='ano_fundacao',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Associacao',
        ),
        migrations.DeleteModel(
            name='Competicao',
        ),
        migrations.DeleteModel(
            name='Jogador',
        ),
        migrations.DeleteModel(
            name='Jogo',
        ),
    ]
