# Generated by Django 3.2 on 2025-01-21 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssociacaoFutebol',
        ),
        migrations.RemoveField(
            model_name='competicao',
            name='formato_competicao',
        ),
        migrations.RemoveField(
            model_name='equipa',
            name='clube',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='posicao',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='clube_casa',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='clube_fora',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='competicao',
        ),
        migrations.DeleteModel(
            name='Clube',
        ),
        migrations.DeleteModel(
            name='Competicao',
        ),
        migrations.DeleteModel(
            name='Equipa',
        ),
        migrations.DeleteModel(
            name='FormatoCompeticao',
        ),
        migrations.DeleteModel(
            name='Jogador',
        ),
        migrations.DeleteModel(
            name='Jogo',
        ),
        migrations.DeleteModel(
            name='PosicaoJogador',
        ),
    ]
