# Generated by Django 3.2.25 on 2024-12-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='utilizador',
            table='p_utilizador',
        ),
    ]
