# Generated by Django 3.2.25 on 2024-12-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_p_jogador_posicao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='P_Jogador',
        ),
    ]
