# Generated by Django 3.2.25 on 2024-11-14 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_competicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('dia', models.DateField()),
                ('hora', models.TimeField()),
                ('clube_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_casa', to='App.clube')),
                ('clube_fora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_fora', to='App.clube')),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.competicao')),
            ],
        ),
    ]
