# Generated by Django 3.2.25 on 2024-11-20 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20241119_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipas', to='App.clube')),
            ],
        ),
    ]
