# Generated by Django 4.2.16 on 2024-11-10 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('alcunha', models.CharField(blank=True, max_length=50)),
                ('estadio', models.CharField(max_length=100)),
                ('ano_fundacao', models.PositiveIntegerField()),
                ('extinto', models.BooleanField(default=False)),
                ('associacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.associacao')),
            ],
        ),
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_formato', models.CharField(max_length=50)),
                ('ano', models.PositiveIntegerField()),
                ('vencedores', models.ManyToManyField(blank=True, related_name='competicoes_vencidas', to='App.clube')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_jogo', models.DateField()),
                ('detalhes', models.TextField()),
                ('clubes', models.ManyToManyField(related_name='jogos', to='App.clube')),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.competicao')),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('altura', models.FloatField()),
                ('data_nascimento', models.DateField()),
                ('clubes_anteriores', models.TextField()),
                ('gols', models.PositiveIntegerField(default=0)),
                ('jogos', models.PositiveIntegerField(default=0)),
                ('em_atividade', models.BooleanField(default=True)),
                ('clube_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.clube')),
            ],
        ),
    ]
