# Generated by Django 3.2.25 on 2024-11-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_jogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clube',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
