# Generated by Django 3.2.25 on 2024-11-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20241115_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clube',
            name='alcunha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
