# Generated by Django 3.2.25 on 2024-11-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_formatocompeticao_posicaojogador'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicaojogador',
            name='descricao',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='posicaojogador',
            name='nome',
            field=models.CharField(max_length=25),
        ),
    ]
