# Generated by Django 3.2.25 on 2024-11-19 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_competicao_formato_competicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competicao',
            name='formato_competicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competicoes', to='App.formatocompeticao'),
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('situacao', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('num_camisola', models.IntegerField()),
                ('posicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='App.posicaojogador')),
            ],
        ),
    ]
